collection_name: agent
persist_diretory: chroma_db
k: 5
data_path: data 
md5_hex_store: md5.text, 
allow_knwoledge_file_type: ["txt", 'pdf', "json"]

chunk_size: 200
chunk_overlap: 20
separator : ["\n\n", "?", ".", ":", "\n"]