main_prompt_path: prompts/main_prompt.txt
rag_sumarize_prompt_path: prompts/rag_sumarize.txt
report_prompt_path: prompts/report_prompt.txt 
blacklist_path: prompts/blacklist.json
intent_prompt_path: prompts/intent.txt
sql_bello_prompt_path: prompts/sql_bello_prompt.txt